"""empty message

Revision ID: 61f2df7fd433
Revises: 
Create Date: 2016-11-28 17:05:07.143060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f2df7fd433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_messenger_id', sa.BigInteger(), nullable=True),
    sa.Column('imgur_account_id', sa.Integer(), nullable=True),
    sa.Column('imgur_username', sa.String(length=400), nullable=True),
    sa.Column('imgur_token', sa.String(length=200), nullable=True),
    sa.Column('imgur_refresh_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fb_messenger_id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_url', sa.String(length=4000), nullable=True),
    sa.Column('imgur_id', sa.String(length=1000), nullable=True),
    sa.Column('imgur_url', sa.String(length=4000), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('picture')
    op.drop_table('tag')
    op.drop_table('account')
    ### end Alembic commands ###
